import JSZip from 'jszip';
import { saveAs } from 'file-saver';

interface AgentConfig {
  agentName: string;
  stakeAmount: string;
  rewardThreshold: string;
  pollInterval: string;
  rpcUrl: string;
}

export async function generateAgentPackage(config: AgentConfig): Promise<void> {
  const zip = new JSZip();
  const folder = zip.folder('nexusclaw-agent')!;

  folder.file('.env.example', `# ==========================================
# NEXUSCLAW AGENT — ${config.agentName.toUpperCase()}
# Generated by nexusclaw.tech/start-agent
# ==========================================

# RPC Base Mainnet
RPC_URL=${config.rpcUrl}

# YOUR AGENT WALLET PRIVATE KEY
# Create a dedicated wallet in MetaMask and paste the private key here
# NEVER use your main wallet private key
PRIVATE_KEY_AGENT=0xYOUR_DEDICATED_AGENT_WALLET_PRIVATE_KEY

# NexusClaw Contracts (Base Mainnet — do not change)
STAKING_ADDRESS=0xD209c27375D1B5916f677F39d5f320E67DD4FaFe
TOKEN_ADDRESS=0xFC68E8aEe3A2e717DebBBBd9f6b2Db5Dd3Ed90E6

# Agent Configuration
MIN_REWARD_CLAW=${config.rewardThreshold}
POLL_INTERVAL_MINUTES=${config.pollInterval}
`);

  folder.file('README.md', `# 🦞 ${config.agentName} — NexusClaw Agent v1

Generated by nexusclaw.tech/start-agent

## Quick Start

1. Create a dedicated MetaMask wallet on Base Mainnet
2. Send $NEXUSCLAW tokens and 0.005 ETH to that wallet
3. Copy .env.example to .env
4. Fill in PRIVATE_KEY_AGENT
5. Run: npm install && node agent-core.js

## Your Configuration

- Stake Amount: ${config.stakeAmount} $NEXUSCLAW
- Reward Threshold: ${config.rewardThreshold} $NEXUSCLAW
- Poll Interval: ${config.pollInterval} minutes

## Security

⚠️ NEVER share your private key
⚠️ NEVER commit .env to GitHub
⚠️ Use a dedicated wallet — not your main wallet

## Links

- Dashboard: https://nexusclaw.tech
- Leaderboard: https://nexusclaw.tech/leaderboard
- Contract: https://basescan.org/address/0xD209c27375D1B5916f677F39d5f320E67DD4FaFe
`);

  folder.file('package.json', JSON.stringify({
    name: 'nexusclaw-agent',
    version: '1.0.0',
    description: `NexusClaw AutoCompounder — ${config.agentName}`,
    main: 'agent-core.js',
    scripts: { start: 'node agent-core.js' },
    dependencies: { viem: '^2.0.0', dotenv: '^16.4.0' },
    engines: { node: '>=18.0.0' },
  }, null, 2));

  try {
    const response = await fetch(
      'https://raw.githubusercontent.com/kashikai/nexusclaw/main/agent-v1/agent-core.js'
    );
    if (response.ok) {
      const agentCode = await response.text();
      folder.file('agent-core.js', agentCode);
    } else {
      throw new Error('fetch failed');
    }
  } catch {
    folder.file('agent-core.js', '// Download failed. Get the latest version at:\n// https://github.com/kashikai/nexusclaw/tree/main/agent-v1\n');
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${config.agentName.toLowerCase().replace(/\s+/g, '-')}-nexusclaw-agent.zip`);
}
