import JSZip from 'jszip';
import { saveAs } from 'file-saver';

const GITHUB_RAW = 'https://raw.githubusercontent.com/kashikai/nexusclaw/main/agent-v1';

interface AgentConfig {
  agentName: string;
  stakeAmount: string;
  rewardThreshold: string;
  pollInterval: string;
  rpcUrl: string;
}

async function fetchFile(filename: string): Promise<string | null> {
  try {
    const res = await fetch(`${GITHUB_RAW}/${filename}`);
    if (!res.ok) return null;
    return await res.text();
  } catch {
    return null;
  }
}

export async function generateAgentPackage(config: AgentConfig): Promise<void> {
  const zip = new JSZip();
  const folder = zip.folder('nexusclaw-agent')!;

  // Fetch agent-core.js and setup.js from GitHub in parallel
  const [agentCore, setupWizard] = await Promise.all([
    fetchFile('agent-core.js'),
    fetchFile('setup.js'),
  ]);

  folder.file(
    'agent-core.js',
    agentCore ?? '// Download failed. Get it at:\n// https://github.com/kashikai/nexusclaw/tree/main/agent-v1\n'
  );

  folder.file(
    'setup.js',
    setupWizard ?? '// Download failed. Get it at:\n// https://github.com/kashikai/nexusclaw/tree/main/agent-v1\n'
  );

  folder.file('.env.example', `# ============================================================
# NEXUSCLAW AGENT — ${config.agentName.toUpperCase()}
# Generated by nexusclaw.tech/start-agent
# ============================================================

# Base Mainnet RPC
RPC_URL=${config.rpcUrl}

# YOUR AGENT WALLET PRIVATE KEY
# ⚠  Create a dedicated MetaMask wallet — NEVER use your main wallet
# ⚠  Export: MetaMask → Account → ⋮ → Account Details → Export Private Key
PRIVATE_KEY_AGENT=0xYOUR_DEDICATED_AGENT_WALLET_PRIVATE_KEY

# NexusClaw Contracts (Base Mainnet — do not change)
STAKING_ADDRESS=0xD209c27375D1B5916f677F39d5f320E67DD4FaFe
TOKEN_ADDRESS=0xFC68E8aEe3A2e717DebBBBd9f6b2Db5Dd3Ed90E6

# Agent Configuration (customized for you)
MIN_REWARD_CLAW=${config.rewardThreshold}
POLL_INTERVAL_MINUTES=${config.pollInterval}
`);

  folder.file('README.md', `# 🦞 ${config.agentName} — NexusClaw Agent v1

Generated by nexusclaw.tech/start-agent

## Quick Start

\`\`\`bash
# 1. Run the setup wizard — checks Node.js, installs deps, generates .env
node setup.js

# 2. Open .env and add your private key (the wizard will tell you how)

# 3. Launch
node agent-core.js
\`\`\`

## Your Configuration

| Setting | Value |
|---|---|
| Stake Amount | ${config.stakeAmount} $NEXUSCLAW |
| Auto-claim Threshold | ${config.rewardThreshold} $NEXUSCLAW |
| Check Interval | Every ${config.pollInterval} minutes |

## Security

- Your private key never leaves your machine
- Never share your .env file
- Never commit .env to GitHub (.gitignore protects you)
- Use a dedicated wallet — not your main wallet

## Links

- Dashboard: https://nexusclaw.tech
- Leaderboard: https://nexusclaw.tech/leaderboard
- Support: https://t.me/nexusclaw
`);

  folder.file('package.json', JSON.stringify({
    name: 'nexusclaw-agent',
    version: '1.0.0',
    description: `NexusClaw AutoCompounder — ${config.agentName}`,
    type: 'module',
    main: 'agent-core.js',
    scripts: {
      start: 'node agent-core.js',
      setup: 'node setup.js',
    },
    dependencies: { viem: '^2.0.0', dotenv: '^16.4.0' },
    engines: { node: '>=18.0.0' },
  }, null, 2));

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${config.agentName.toLowerCase().replace(/\s+/g, '-')}-nexusclaw-agent.zip`);
}
